name: Export CloudWatch Logs

on:
  schedule:
    - cron: '*/3 * * * *'  # Runs at 2 AM on the 1st of every month

jobs:
  export-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1  # e.g., us-west-2

      - name: Export Logs
        run: |
          aws logs create-export-task --log-group-name /aws/rds/instance/green-test/postgresql  --from $(($(date -d "15 days ago" +%s) * 1000)) --to $(($(date -d "1 days ago" +%s) * 1000)) --destination db-logs-test --destination-prefix postgresql-test-logs
